# Install MySQL Server Nodes

- hosts: [Test]
  user: semaphore
  become: yes
  become_user: root
  become_method: su
  tasks:
    - include_tasks: task_mysql_pre_checks.yml
    - include_tasks: task_mysql_os.yml
    - include_tasks: task_mysql_upload.yml
    - include_tasks: task_mysql_config.yml
    - include_tasks: task_mysql_init.yml

